name: Create and Configure Repository

# Define the events that trigger this workflow
on:
  push:
    branches:
      - main # Trigger on push events to the main branch
  pull_request:
    branches:
      - main # Trigger on pull request events targeting the main branch
  schedule:
    - cron: '0 0 * * 0' # Trigger on a schedule (every Sunday at midnight)
  repository_dispatch:
    types: [create-repo] # Trigger on custom repository dispatch events of type 'create-repo'
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  create-repo:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 # Checkout the repository code

    - name: Install GitHub CLI
      run: sudo apt-get install -y gh # Install GitHub CLI on the runner

    - name: Authenticate with GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub token stored in secrets
      run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}" # Authenticate with GitHub CLI

    - name: Create new repository
      env:
        REPO_NAME: new-repo-name # Name of the new repository
        REPO_DESCRIPTION: "Description of the new repository" # Description of the new repository
      run: gh repo create $REPO_NAME --public --description "$REPO_DESCRIPTION" # Create a new public repository with the specified name and description

    - name: Add README
      run: |
        echo "# $REPO_NAME" > README.md # Create a README file with the repository name as the title
        git init # Initialize a new Git repository
        git add README.md # Add the README file to the repository
        git commit -m "Add README" # Commit the README file
        git branch -M main # Rename the default branch to main
        git remote add origin https://github.com/${{ github.repository_owner }}/$REPO_NAME.git # Add the remote origin
        git push -u origin main # Push the changes to the remote repository