name: Inject Secrets Example

# Define the events that trigger this workflow
on:
  push:
    branches:
      - main # Trigger on push events to the main branch
  pull_request:
    branches:
      - main # Trigger on pull request events targeting the main branch
  schedule:
    - cron: '0 0 * * 0' # Trigger on a schedule (every Sunday at midnight)
  repository_dispatch:
    types: [inject-secrets] # Trigger on custom repository dispatch events of type 'inject-secrets'
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  inject-secrets:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 # Checkout the repository code

    - name: Pre-action: Inject Secrets
      env:
        SECRET_ONE: ${{ secrets.SECRET_ONE || 'default_secret_one' }} # Inject SECRET_ONE or use default
        SECRET_TWO: ${{ secrets.SECRET_TWO || 'default_secret_two' }} # Inject SECRET_TWO or use default
      run: |
        echo "SECRET_ONE is set to $SECRET_ONE" # Confirm that SECRET_ONE is set
        echo "SECRET_TWO is set to $SECRET_TWO" # Confirm that SECRET_TWO is set

    - name: Use Injected Secrets
      env:
        SECRET_ONE: ${{ secrets.SECRET_ONE || 'default_secret_one' }} # Use SECRET_ONE or default
        SECRET_TWO: ${{ secrets.SECRET_TWO || 'default_secret_two' }} # Use SECRET_TWO or default
      run: |
        # Example commands using the secrets
        echo "Using SECRET_ONE: $SECRET_ONE"
        echo "Using SECRET_TWO: $SECRET_TWO"